services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app  # Bind mount pour hot-reload code API

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
    environment:
      API_URL: "http://api:8000"
    depends_on:
      - api
    volumes:
      - ./ui:/app  # Bind mount pour hot-reload Streamlit